"""Abbreviations in the documents.  Used for merging string clusters (merge_clusters.py)."""


non_token_abbrs = {'nat l': ['national'],
                   '/pol': [''],
                   'iss/': [''],
                   ' s ':   ['\'s ']}

abbrs = {'com': ['committee'],
         'cnty': ['county'],
         'oppty': ['opportunity'],
         'opty': ['opportunity'],
         'ntl': ['national'],
         'assc': ['association'],
         '/': [''],
         '4': ['for', ''],
         'the': [''],
         'fr': ['for'],
         'order': [''],
         'estimate': [''],
         'est': [''],
         'comptrl': ['comptroller'],
         'comp': ['comptroller'],
         'flight': [''],
         'contract': [''],
         'political': [''],
         'pol': ['', 'political'],
         'endng': ['ending'],
         'spndng': ['spending'],
         'billing': [''],
         'cycle': [''],
         'dates': [''],
         'act': ['action'],
         'add': [''],
         'am': ['american', 'americans'],
         'amer': ['american', 'americans'],
         'amr': ['american', 'americans'],
         'asn': ['association'],
         'assn': ['association'],
         'assoc': ['association'],
         'att': ['attorney'],
         'cand': [''],
         'cham': ['chamber'],
         'clb': ['club'],
         'cmt': ['committee'],
         'cmte': ['committee'],
         'coal': ['coalition'],
         'coalit': ['coalition'],
         'com': ['commissioner', 'commission'],
         'comm': ['commerce', 'committee', 'commissioner', 'commission'],
         'con': ['congress', 'congressional'],
         'cong': ['congress', 'congressional'],
         'congr': ['congress', 'congressional'],
         'congres': ['congress', 'congressional'],
         'ct': ['court'],
         'da': ['district attorney'],
         'dem': ['', 'democracy', 'democratic', 'democrats'],
         'dist': ['', 'district'],
         'emp': ['employees', 'employment'],
         'empl': ['employees', 'employment'],
         'fnd': ['fund'],
         'fndn': ['foundation'],
         'fnds': ['friends'],
         'frnds': ['friends'],
         'fun': ['fund'],
         's': ['senate'],
         'h': ['house', 'house of representatives'],
         'c': ['congress'],
         'gen': ['general'],
         'gov': ['government', 'governor', 'governors'],
         'govt': ['government'],
         'govern': ['government', 'governor', 'governors'],
         'cty': ['city'],
         'i': [''],
         'intl': ['international'],
         'iss': [''],
         'issue': [''],
         'l': [''],
         'lead': ['leadership'],
         'leag': ['league'],
         'ltgov': ['lieutenant governor', 'lt gov'],
         'lt': ['lieutenant', 'lieutenant governor'],
         'maj': ['majority'],
         'natl': ['national'],
         'nat': ['national'],
         'part': ['partners'],
         'prty': ['party'],
         'pty': ['party'],
         'pub': ['public'],
         'edu': ['education'],
         'ed': ['education'],
         'rep': ['', 'representative', 'representatives', 'republican', 'republicans'],
         'sec': ['secretary'],
         'sect': ['secretary'],
         'sena': ['senate'],
         'sn': ['senate', 'senator'],
         'sen': ['senate', 'senator'],
         'serv': ['service'],
         'se': ['senate'],
         'sked': [''],
         'st': ['state'],
         'sup': ['supreme'],
         'wk': [''],
         'week': ['']
         }
